services:
  localstack:
    container_name: localstack
    image: floci/floci:latest-compat
    ports:
      - "4566:4566"
    environment:
      - SERVICES=dynamodb,s3
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - ../localstack/provision.sh:/etc/localstack/init/ready.d/provision.sh

  kms:
    container_name: local-kms
    image: nsmithuk/local-kms
    environment:
      - KMS_ACCOUNT_ID=000000000000
      - KMS_REGION=eu-west-2
      - KMS_SEED_PATH=/init/seed.yaml
    volumes:
      - ../localstack/seed.yaml:/init/seed.yaml

  imposter:
    container_name: imposter-mock
    image: outofcoffee/imposter
    ports:
      - "8001:8080"
    volumes:
      - ./mocks/config:/opt/imposter/config
  cri:
    container_name: example-cri
    platform: linux/amd64
    build:
      context: ..
      dockerfile: ./Dockerfile
    environment:
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_REGION=eu-west-2
      - CREDENTIAL_STORE_URL=http://imposter-mock:8080
      - ENVIRONMENT=ci
      - LOCALSTACK_ENDPOINT=http://localstack:4566
      - KMS_ENDPOINT=http://local-kms:8080
      - ONE_LOGIN_AUTH_SERVER_URL=http://test-harness:3001
      - SELF_URL=http://example-cri:8080
      - STATUS_LIST_URL=http://imposter-mock:8080
    ports:
      - "8080:8080"
    depends_on:
      - localstack
      - kms
      - imposter

networks:
  default:
    name: integration-tests
