version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    target-branch: main
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: chore
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    target-branch: main
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: chore
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
    target-branch: main
    labels:
      - dependabot
      - dependencies
    commit-message:
      prefix: chore