version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      github-actions-updates:
        patterns:
          - "*"
  - package-ecosystem: "gradle"
    directory: "/example-credential-issuer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      gradle-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "docker"
    directory: "/example-credential-issuer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    groups:
      docker-updates:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directories: "/document-signing-certificate-issuer"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    labels:
      - dependencies
    commit-message:
      prefix: chore
    open-pull-requests-limit: 5
    versioning-strategy: increase
    groups:
      npm-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
