repos:
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, chore, docs, style, refactor, test, build, ci, perf, revert]

  - repo: local
    hooks:
      - id: cri-spotless
        name: CRI - Java format check
        language: system
        entry: bash -c 'cd example-credential-issuer && ./gradlew spotlessCheck -q'
        files: ^example-credential-issuer/.*\.(java|md)$
        stages: [pre-commit]

      - id: cri-checkov
        name: CRI - Infrastructure static analysis
        language: system
        entry: bash -c 'cd example-credential-issuer && ./gradlew checkov'
        files: ^example-credential-issuer/deploy/template.yaml
        stages: [pre-commit]

      - id: cri-tests
        name: CRI - Gradle unit tests
        language: system
        entry: bash -c 'cd example-credential-issuer && ./gradlew test -q'
        files: ^example-credential-issuer/.*\.java$
        stages: [pre-push]

  - repo: local
    hooks:
      - id: dsc-eslint-ts
        name: DSC - ESLint linter
        language: system
        entry: bash -c 'cd document-signing-certificate-issuer && npm run lint'
        files: ^document-signing-certificate-issuer/.*\.(ts|md)$
        stages: [pre-commit]

      - id: dsc-prettier-ts
        name: DSC - Prettier format check
        language: system
        entry: bash -c 'cd document-signing-certificate-issuer && npm run format:check'
        files: ^document-signing-certificate-issuer/.*\.(ts|md|yaml)$
        stages: [pre-commit]

      - id: dsc-jest-tests
        name: DSC - Jest unit tests
        language: system
        entry: bash -c 'cd document-signing-certificate-issuer && npm run test'
        files: ^document-signing-certificate-issuer/.*\.ts$
        stages: [pre-push]

      - id: dsc-checkov
        name: DSC - Infrastructure static analysis
        language: system
        entry: bash -c 'cd document-signing-certificate-issuer && npm run checkov'
        files: ^document-signing-certificate-issuer/template.yaml
        stages: [pre-commit]