services:
  localstack:
    container_name: localstack_credentialIssuer
    image: localstack/localstack:latest
    ports:
      - "4560:4566"
    environment:
      - SERVICES=dynamodb,kms
      - AWS_ACCESS_KEY_ID=na
      - AWS_SECRET_ACCESS_KEY=na
      - AWS_DEFAULT_REGION=eu-west-2
    volumes:
      - ./localstack/provision.sh:/etc/localstack/init/ready.d/provision.sh