FROM outofcoffee/imposter:latest
COPY openapi.yaml /opt/imposter/config/
COPY imposter-config.yaml /opt/imposter/config/
COPY authorize.groovy /opt/imposter/config/
COPY redirect.groovy /opt/imposter/config/
COPY token.groovy /opt/imposter/config/
