server:
  requestLog:
    appenders:
      - type: console
        layout:
          type: access-json
        filterFactories:
          - type: uri
            uris:
              - "/healthcheck"
logging:
  level: INFO
  appenders:
    - type: console
      layout:
        type: json

