export interface DrivingLicenceRequestBody {
  family_name: string;
  given_name: string;
  title: string;
  welsh_licence: string;
  portrait: string;
  "birth-day": string;
  "birth-month": string;
  "birth-year": string;
  birth_place: string;
  "issue-day": string;
  "issue-month": string;
  "issue-year": string;
  "expiry-day": string;
  "expiry-month": string;
  "expiry-year": string;
  issuing_authority: string;
  issuing_country: string;
  document_number: string;
  resident_address: string[];
  resident_postal_code: string;
  resident_city: string;
  fullVehicleCategoryCode: string | string[];
  fullRestrictionCodes: string | string[];
  "fullPrivilegeIssue-day": string | string[];
  "fullPrivilegeIssue-month": string | string[];
  "fullPrivilegeIssue-year": string | string[];
  "fullPrivilegeExpiry-day": string | string[];
  "fullPrivilegeExpiry-month": string | string[];
  "fullPrivilegeExpiry-year": string | string[];
  provisionalVehicleCategoryCode?: string | string[];
  "provisionalPrivilegeIssue-day"?: string | string[];
  "provisionalPrivilegeIssue-month"?: string | string[];
  "provisionalPrivilegeIssue-year"?: string | string[];
  "provisionalPrivilegeExpiry-day"?: string | string[];
  "provisionalPrivilegeExpiry-month"?: string | string[];
  "provisionalPrivilegeExpiry-year"?: string | string[];
  credentialTtl: string;
  throwError: string;
}
