AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  private-ca

  Sample SAM Template for private-ca

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - app.ts

  RootCA:
    Type: AWS::ACMPCA::CertificateAuthority
    Properties:
      Type: ROOT
      KeyAlgorithm: EC_prime256v1
      SigningAlgorithm: SHA256WITHECDSA
      Subject:
        Country: UK
#        Organization: string
#        OrganizationalUnit: string
#        DistinguishedNameQualifier: string
#        State: string
        CommonName: 'mDL IACA Root'
#        SerialNumber: string
#        Locality: string
#        Title: string
#        Surname: string
#        GivenName: string
#        Initials: DG
#        Pseudonym: string
#        GenerationQualifier: DBG
      RevocationConfiguration:
        OcspConfiguration:
          Enabled: true

  RootCACertificate:
    Type: AWS::ACMPCA::Certificate
    Properties:
      CertificateAuthorityArn:
        Ref: RootCA
      CertificateSigningRequest:
        Fn::GetAtt:
          - RootCA
          - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHECDSA
      TemplateArn: arn:aws:acm-pca:::template/BlankRootCACertificate_PathLen0_APIPassthrough/V1
      Validity:
        Type: DAYS
        Value: 3285  # 9 years
      ApiPassthrough:
        Extensions:
          CustomExtensions:
            - ObjectIdentifier: "2.5.29.31"
              Value: "MEgwRqBEoEKGQGh0dHA6Ly9leGFtcGxlLmNvbS9jcmwvMDExNnoxMjMtZHY3YS01OWIxLXg3YmUtMTIzMXY3MjU3MTEzNi5jcmw="
          KeyUsage:
            KeyCertSign: true
            CRLSign: true

  RootCAActivation:
    Type: AWS::ACMPCA::CertificateAuthorityActivation
    Properties:
      CertificateAuthorityArn:
        Ref: RootCA
      Certificate:
        Fn::GetAtt:
          - RootCACertificate
          - Certificate
      Status: ACTIVE
#  RootCAPermission:
#    Type: AWS::ACMPCA::Permission
#    Properties:
#      Actions:
#        - IssueCertificate
#        - GetCertificate
#        - ListPermissions
#      CertificateAuthorityArn: !Ref RootCA
#      Principal: acm.amazonaws.com
#  SubordinateCAOne:
#    Type: AWS::ACMPCA::CertificateAuthority
#    Properties:
#      Type: SUBORDINATE
#      KeyAlgorithm: RSA_2048
#      SigningAlgorithm: SHA256WITHRSA
#      Subject:
#        Country: US
#        Organization: string
#        OrganizationalUnit: string
#        DistinguishedNameQualifier: string
#        State: string
#        CommonName: Sub1
#        SerialNumber: string
#        Locality: string
#        Title: string
#        Surname: string
#        GivenName: string
#        Initials: DG
#        Pseudonym: string
#        GenerationQualifier: DBG
#      RevocationConfiguration: {}
#      Tags: []
#  SubordinateCAOneCACertificate:
#    DependsOn: RootCAActivation
#    Type: AWS::ACMPCA::Certificate
#    Properties:
#      CertificateAuthorityArn:
#        Ref: RootCA
#      CertificateSigningRequest:
#        Fn::GetAtt:
#          - SubordinateCAOne
#          - CertificateSigningRequest
#      SigningAlgorithm: SHA256WITHRSA
#      TemplateArn: arn:aws:acm-pca:::template/SubordinateCACertificate_PathLen3/V1
#      Validity:
#        Type: DAYS
#        Value: 90
#  SubordinateCAOneActivation:
#    Type: AWS::ACMPCA::CertificateAuthorityActivation
#    Properties:
#      CertificateAuthorityArn:
#        Ref: SubordinateCAOne
#      Certificate:
#        Fn::GetAtt:
#          - SubordinateCAOneCACertificate
#          - Certificate
#      CertificateChain:
#        Fn::GetAtt:
#          - RootCAActivation
#          - CompleteCertificateChain
#      Status: ACTIVE
#  SubordinateCAOnePermission:
#    Type: AWS::ACMPCA::Permission
#    Properties:
#      Actions:
#        - IssueCertificate
#        - GetCertificate
#        - ListPermissions
#      CertificateAuthorityArn: !Ref SubordinateCAOne
#      Principal: acm.amazonaws.com
#  SubordinateCATwo:
#    Type: AWS::ACMPCA::CertificateAuthority
#    Properties:
#      Type: SUBORDINATE
#      KeyAlgorithm: RSA_2048
#      SigningAlgorithm: SHA256WITHRSA
#      Subject:
#        Country: US
#        Organization: string
#        OrganizationalUnit: string
#        DistinguishedNameQualifier: string
#        State: string
#        SerialNumber: string
#        Locality: string
#        Title: string
#        Surname: string
#        GivenName: string
#        Initials: DG
#        Pseudonym: string
#        GenerationQualifier: DBG
#      Tags:
#        - Key: Key1
#          Value: Value1
#        - Key: Key2
#          Value: Value2
#  SubordinateCATwoCACertificate:
#    DependsOn: SubordinateCAOneActivation
#    Type: AWS::ACMPCA::Certificate
#    Properties:
#      CertificateAuthorityArn:
#        Ref: SubordinateCAOne
#      CertificateSigningRequest:
#        Fn::GetAtt:
#          - SubordinateCATwo
#          - CertificateSigningRequest
#      SigningAlgorithm: SHA256WITHRSA
#      TemplateArn: arn:aws:acm-pca:::template/SubordinateCACertificate_PathLen2/V1
#      Validity:
#        Type: DAYS
#        Value: 80
#  SubordinateCATwoActivation:
#    Type: AWS::ACMPCA::CertificateAuthorityActivation
#    Properties:
#      CertificateAuthorityArn:
#        Ref: SubordinateCATwo
#      Certificate:
#        Fn::GetAtt:
#          - SubordinateCATwoCACertificate
#          - Certificate
#      CertificateChain:
#        Fn::GetAtt:
#          - SubordinateCAOneActivation
#          - CompleteCertificateChain
#  SubordinateCATwoPermission:
#    Type: AWS::ACMPCA::Permission
#    Properties:
#      Actions:
#        - IssueCertificate
#        - GetCertificate
#        - ListPermissions
#      CertificateAuthorityArn: !Ref SubordinateCATwo
#      Principal: acm.amazonaws.com
#  EndEntityCertificate:
#    DependsOn: SubordinateCATwoActivation
#    Type: AWS::ACMPCA::Certificate
#    Properties:
#      CertificateAuthorityArn:
#        Ref: SubordinateCATwo
#      CertificateSigningRequest:
#        Fn::Join:
#          - "\n"
#          - - "-----BEGIN CERTIFICATE REQUEST-----"
#            - MIICvDCCAaQCAQAwdzELMAkGA1UEBhMCVVMxDTALBgNVBAgMBFV0YWgxDzANBgNV
#            - BAcMBkxpbmRvbjEWMBQGA1UECgwNRGlnaUNlcnQgSW5jLjERMA8GA1UECwwIRGln
#            - aUNlcnQxHTAbBgNVBAMMFGV4YW1wbGUuZGlnaWNlcnQuY29tMIIBIjANBgkqhkiG
#            - 9w0BAQEFAAOCAQ8AMIIBCgKCAQEA8+To7d+2kPWeBv/orU3LVbJwDrSQbeKamCmo
#            - wp5bqDxIwV20zqRb7APUOKYoVEFFOEQs6T6gImnIolhbiH6m4zgZ/CPvWBOkZc+c
#            - 1Po2EmvBz+AD5sBdT5kzGQA6NbWyZGldxRthNLOs1efOhdnWFuhI162qmcflgpiI
#            - WDuwq4C9f+YkeJhNn9dF5+owm8cOQmDrV8NNdiTqin8q3qYAHHJRW28glJUCZkTZ
#            - wIaSR6crBQ8TbYNE0dc+Caa3DOIkz1EOsHWzTx+n0zKfqcbgXi4DJx+C1bjptYPR
#            - BPZL8DAeWuA8ebudVT44yEp82G96/Ggcf7F33xMxe0yc+Xa6owIDAQABoAAwDQYJ
#            - KoZIhvcNAQEFBQADggEBAB0kcrFccSmFDmxox0Ne01UIqSsDqHgL+XmHTXJwre6D
#            - hJSZwbvEtOK0G3+dr4Fs11WuUNt5qcLsx5a8uk4G6AKHMzuhLsJ7XZjgmQXGECpY
#            - Q4mC3yT3ZoCGpIXbw+iP3lmEEXgaQL0Tx5LFl/okKbKYwIqNiyKWOMj7ZR/wxWg/
#            - ZDGRs55xuoeLDJ/ZRFf9bI+IaCUd1YrfYcHIl3G87Av+r49YVwqRDT0VDV7uLgqn
#            - 29XI1PpVUNCPQGn9p/eX6Qo7vpDaPybRtA2R7XLKjQaF9oXWeCUqy1hvJac9QFO2
#            - 97Ob1alpHPoZ7mWiEuJwjBPii6a9M9G30nUo39lBi1w=
#            - "-----END CERTIFICATE REQUEST-----"
#      SigningAlgorithm: SHA256WITHRSA
#      Validity:
#        Type: DAYS
#        Value: 70
Outputs:
#  CompleteCertificateChain:
#    Value:
#      Fn::GetAtt:
#        - SubordinateCATwoActivation
#        - CompleteCertificateChain
#  CertificateArn:
#    Value:
#      Fn::GetAtt:
#        - EndEntityCertificate
#        - Arn

  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value: !GetAtt HelloWorldFunctionRole.Arn
