AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  private-ca

  Sample SAM Template for private-ca

Resources:
  RootCA:
    Type: AWS::ACMPCA::CertificateAuthority
    Properties:
      Type: ROOT
      KeyAlgorithm: EC_prime256v1
      SigningAlgorithm: SHA256WITHECDSA
      Subject:
        Country: UK
#        Organization: string
#        OrganizationalUnit: string
#        DistinguishedNameQualifier: string
#        State: string
        CommonName: 'mDL IACA Root'
#        SerialNumber: string
#        Locality: string
#        Title: string
#        Surname: string
#        GivenName: string
#        Initials: DG
#        Pseudonym: string
#        GenerationQualifier: DBG
      RevocationConfiguration:
        OcspConfiguration:
          Enabled: true

  RootCACertificate:
    Type: AWS::ACMPCA::Certificate
    Properties:
      CertificateAuthorityArn:
        Ref: RootCA
      CertificateSigningRequest:
        Fn::GetAtt:
          - RootCA
          - CertificateSigningRequest
      SigningAlgorithm: SHA256WITHECDSA
      TemplateArn: arn:aws:acm-pca:::template/BlankRootCACertificate_PathLen0_APIPassthrough/V1
      Validity:
        Type: DAYS
        Value: 3285  # 9 years
      ApiPassthrough:
        Extensions:
          CustomExtensions:
            - ObjectIdentifier: "2.5.29.31"
              Value: "MEgwRqBEoEKGQGh0dHA6Ly9leGFtcGxlLmNvbS9jcmwvMDExNnoxMjMtZHY3YS01OWIxLXg3YmUtMTIzMXY3MjU3MTEzNi5jcmw="
          KeyUsage:
            KeyCertSign: true
            CRLSign: true

  RootCAActivation:
    Type: AWS::ACMPCA::CertificateAuthorityActivation
    Properties:
      CertificateAuthorityArn:
        Ref: RootCA
      Certificate:
        Fn::GetAtt:
          - RootCACertificate
          - Certificate
      Status: ACTIVE

  DocumentSigningKey:
    Type: AWS::KMS::Key
    Properties:
      KeySpec: ECC_NIST_P256
      KeyUsage: SIGN_VERIFY
      Description: !Sub "Example Document Signing Key for ${AWS::StackName}"
      Enabled: true
      PendingWindowInDays: 7

  DocumentSigningKeyAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub "alias/${AWS::StackName}-doc-signing-key"
      TargetKeyId: !Ref DocumentSigningKey

Outputs:
  RootCertificate:
    Value:
      Fn::GetAtt:
        - RootCAActivation
        - CompleteCertificateChain
  RootCertificateArn:
    Value:
      Fn::GetAtt:
        - RootCACertificate
        - Arn
