name: DSC Issuer - Deploy to Dev

on:
  workflow_dispatch:
    inputs:
      gitRef:
        description: Input branch name or commit SHA
        required: true
        type: string
        default: main

permissions:
  id-token: write
  contents: read

jobs:
  deploy_artifacts:
    name: Deploy Template to Dev
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      # Check out the repository at the specified branch, tag, or commit
      - name: Check out repository code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # pin@v3
        with:
          ref: ${{ inputs.gitRef }}

      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version-file: document-signing-certificate-issuer/.nvmrc

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # pin@v1-node16
        with:
          role-to-assume: ${{ secrets.DEV_DSC_ISS_GH_ACTIONS_ROLE_ARN }}
          aws-region: eu-west-2

      - name: Set up SAM CLI
        uses: aws-actions/setup-sam@819220f63fb333a9a394dd0a5cab2d8303fd17e2 # pin@v2
        with:
          version: 1.131.0
          use-installer: true

      - name: Run SAM validate
        run: sam validate

      - name: Run SAM build
        run: sam build --cached

      # Upload the built SAM application artifacts to the deployment pipeline S3 bucket
      - name: Upload artifacts
        uses: govuk-one-login/devplatform-upload-action@dc8158079d3976d613515180e543930cdbe73f5f # pin@v3.9.1
        with:
          artifact-bucket-name: ${{ secrets.DEV_DSC_ISS_ARTIFACT_SOURCE_BUCKET_NAME }}
          signing-profile-name: ${{ secrets.DEV_SIGNING_PROFILE_NAME }}
          working-directory: ./document-signing-certificate-issuer
          template-file: .aws-sam/build/template.yaml
