name: Test Harness - Pull Request Checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
    paths:
      - test-harness/**
      - .github/workflows/test-harness-pull-request-checks.yml
  workflow_dispatch:
    inputs:
      gitRef:
        description: Branch name or commit SHA
        required: false
        default: main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-conventional-commits:
    name: Check conventional commits
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          # Pick the PR HEAD instead of the merge commit
          ref: ${{ inputs.gitRef || github.event.pull_request.head.sha }}

      - name: Verify conventional commit standards
        uses: cocogitto/cocogitto-action@52d0023b4396897f1815648e553db2ab8d782f3a # v4.2.0
        with:
          command: check
          args: --from-latest-tag

  run-sonarqube-scan:
    name: Run SonarQube Scan
    uses: ./.github/workflows/test-harness-sonarqube.yml
    permissions:
      contents: read
    with:
      gitRef: ${{ inputs.gitRef || github.event.pull_request.head.sha }}
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build-lint-and-test:
    name: Build, lint and test
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    permissions:
      contents: read
    defaults:
      run:
        working-directory: ./test-harness
    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
          ref: ${{ inputs.gitRef || github.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: test-harness/.nvmrc
          cache: npm
          cache-dependency-path: test-harness/package-lock.json

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run the linter
        run: npm run lint

      - name: Build source code
        run: npm run build

      - name: Run unit tests
        run: npm run test:unit

